---
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: wd
          content-type: application/json
        input:
          destination: wd
          content-type: application/json

      kafka:
        binder:
          zkNodes: 192.168.164.129
          brokers: 192.168.164.129
          input:
            consumer:
              resetOffsets: true
